angular.module('app', [

	/**
	 * partials module
	 * ---------------
	 *
	 * Generated by the build system through the `html2js` task
	 *
	 * Contains all the partials compiled to a single js adding them to
	 * the angular's template cache
	 */
	'partials',
	'ng-soocss',

	/**
	 * routes module
	 * -------------
	 *
	 * Defined in `routes.js`
	 *
	 * Contains all the application routes binding URLs to HTML views
	 *
	 * Controllers are declared in the HTML. That way, a single view can use
	 * multiple controllers in sereral parts
	 */
	'routes',

	/**
	 * ng-soocss module
	 * ---------------
	 * Contains all the directives regarding to soocss components
	 */
	// 'ng-soocss',

	'app.service.session',
	'app.factory.jwtInterceptor',
	'app.test.tontunas'
])

.config(function Config($httpProvider) {
  'use strict';
  /*const casa = 'MUCHO';

  console.log(casa);*/

  // push the pwt interceptors. In each request the jwt token will be added as a header
  $httpProvider.interceptors.push('jwtInterceptor');
})
.run(['testTontunas', function (testTontunas) {
	testTontunas.test1();
}]);
